### ISSUE TITLE
compatibility with jQuery Transit plugin

### ISSUE THREAD

**Issue by ninique** [briangonzalez/jquery.pep.js#103]
When I use this plugin in combination with the jquery transit plugin (http://ricostacruz.com/jquery.transit) , it stops working properly. It no longer moves during dragging; only after you release the mouse and it gets to the "kinetic" part of the motion. 

JSFiddle:
http://jsfiddle.net/U8xsc/

**Comment by bachy** [comment]
hello,
sorry to post on a closed issue
i confirm the incompatibility with jquery.transit
it could be on the readme, could avoid to some to spend time on finding the bug ...
by the way, nice work, and thank you!
