### ISSUE TITLE
Drag becomes really sluggish if CSS transition added

### ISSUE THREAD

**Issue by majimekun** [briangonzalez/jquery.pep.js#151]
Hi Brian

I've noticed the following issue today : 

When I add 
```
-webkit-transition: 0.5s ease-in-out;
transition: 0.5s ease-in-out;
-webkit-transform: scale(1);
transform: scale(1);
```
to an element in my CSS, the drag on this element becomes really sluggish on both PC and mobile ... to the point where it doesn't feel responsive at all anymore.

BUT, if I remove the CSS transforms and apply the same animation by using Velocity.js instead, 
```
$.velocity({
'opacity' : '1',
'scale' : '+=50%'
}, 100, 'linear');
```
Pep becomes fluid again.

Any idea of what's going on?

Cheers

**Comment by karneaud** [comment]
just chiming in here but when using velocityjs ...css transitions are a no no as velocity uses its own and yours will cause a conflict
