### ISSUE TITLE
Restrict drag only one direction 

### ISSUE THREAD

**Issue by mrmarktyy** [briangonzalez/jquery.pep.js#157]
I am using axis: y at the moment, wondering how can i restrict dragging to only one direction (eg only drag up from start position)

Thanks

**Comment by briangonzalez** [comment]
During drag, you'll check the drag direction and return false if in the wrong direction.

**Comment by mrmarktyy** [comment]
Hi @briangonzalez  thanks for you quick response. I tried what you said, it seems the drag has already happened, it won't prevent drag in the first though drag callback returns false.

**Comment by mrmarktyy** [comment]
@briangonzalez, drag : function () {return false;} seems work in v0.6.3,  but not in master.

**Comment by Joeao** [comment]
That makes sense, the change in Master since 0.6.3 calls the move before the custom event. It will move before having a chance to return false.
