### ISSUE TITLE
jquery/PEP vs jquery.pep.js

### ISSUE THREAD

**Issue by thijsBreker** [briangonzalez/jquery.pep.js#159]
I was confusing this plug-in with the pointer events poly-fill by the jquery team: https://github.com/jquery/PEP/ Could you perhaps mention the poly-fill somewhere in your readme?

**Comment by Joeao** [comment]
I think the first line of the readme makes it clear that this isn't anything to do with Pointer Events Polyfill. I'm curious as to how far into implementation you got before realising that this isn't the project you were looking for.

**Comment by thijsBreker** [comment]
I didn't implementing anything, currently busy researching and trying to figure out what will be best for this project. You're right that the readme states that it's a drag & drop library but you got to agree that the naming is a bit unfortunate now that the polyfill is also called pep.
