### ISSUE TITLE
Do not start the drag until...

### ISSUE THREAD

**Issue by alexismangin** [briangonzalez/jquery.pep.js#173]
I was wondering if there is a way to start to drag the element only until a couple of pixels are reached? For example, when I click down and move the mouse 5 pixels to the right, it will start to drag the element and not before it reaches those 5 pixels.
Thanks

**Comment by Joeao** [comment]
You could set the grid as [5,5], then on the drag event see if the start position is beyond 5 pixels from the starting point, if so set the grid to [0,0].
I've not tested this myself, it's worth trying though.
