### ISSUE TITLE
select fields disabled

### ISSUE THREAD

**Issue by peteratomic** [briangonzalez/jquery.pep.js#175]
Can't seem to use these draggable boxes with a select field. Have tried digging thru the CSS to see if there's a conflict but can't find anything obvious.

Any ideas what could be blocking the functioning of a select drop down?

**Comment by patricepellier** [comment]
Hello did you find an issue to use <select> balise with pep ?

**Comment by Anaphase** [comment]
Are you trying to make the select box draggable? How would you ever choose an option from the list if that were the case? You could try setting the `shouldPreventDefault` to false. If you're trying to actually USE a select box inside of a draggable element, set `elementsWithInteraction` to `['input', 'select'].

**Comment by patricepellier** [comment]
thank's
