### ISSUE TITLE
Issue when zooming / using with another library?

### ISSUE THREAD

**Issue by simonmacfadyen** [briangonzalez/jquery.pep.js#183]
I wanted to add kinetic / easing to a library I am currently using, [svg-pan-zoom](https://github.com/ariutta/svg-pan-zoom). 

e.g. http://codepen.io/simonmacfadyen/pen/JXoBqx

As you can see, it works to pan the container, but when the container is zoomed by **svg-pan-zoom**, the container is hidden/overflow hidden.

Can you see anyway around this? I'd like to add some easing to svg-pan-zoom.

**Comment by bindea-mihai** [comment]
+1
I am also having problem with dragging an element from a div that has overflow set on it to another div. Because of the overflow, the element disappears. Do you see a workaround here?

**Comment by Anaphase** [comment]
Well, at least for @simonmacfadyen's CodePen, you can solve the issue by putting `overflow: visible;` on the SVG element. You could then wrap that whole thing in a fixed size div with `overflow: hidden;` on it if you wanted. @bindea-mihai, if you want to provide a simple CodePen demonstrating your use case I'd be happy to take a look.

**Comment by Joeao** [comment]
@bindea-mihai my solution is to append the element to the body when beginning the drag, setting its new position relative to the window so the placement doesn't jump. Then append it onto the dropzone on release.
