### ISSUE TITLE
Using pep with helper (by analogy with draggabale)

### ISSUE THREAD

**Issue by user129301** [briangonzalez/jquery.pep.js#184]
I'm migrating from $.draggable to $.pep - wonder if I can use helper option available with draggables or what my options are anyway? thanks.

**Comment by seanCodes** [comment]
Options are documented in the README.md (not sure if that's what you were asking)

Closing this issue for now but if you still have questions feel free to create a new issue.

**Comment by Anaphase** [comment]
Seems like he's asking if there's something like [this](http://api.jqueryui.com/draggable/#option-helper) available in pep. Basically, having one element act as the trigger for dragging another element I think? Nothing like that exists in pep as far as I'm aware.
