### ISSUE TITLE
Is there a way to add position:absolute only when the object was tapped/clicked?

### ISSUE THREAD

**Issue by PierBover** [briangonzalez/jquery.pep.js#188]
Right now when using `.pep()` it adds `position:absolute;` to the object.

Is there a way to disable this and only add position absolute after the object was tapped?

**Comment by Anaphase** [comment]
From [inspecting the source](https://github.com/briangonzalez/jquery.pep.js/blob/master/src/jquery.pep.js#L755), I would say probably not. You could just attach the pep handler on first click? Something like this:

```javascript
$('.target-element').one('click', function() {
  $(this).pep()
})
```

**Comment by PierBover** [comment]
Thanks @Anaphase 

Why didn't I think of that?

I need more sleep...

**Comment by aidan2129** [comment]
Is there a method to stop pep on release e.g. check when it's being dragged and remove position absolute when the item is not being dragged ?

**Comment by Anaphase** [comment]
@aidan2129, I kinda doubt it, because then it wouldn't be positioned anymore so what's the point of dragging? There are the `stop` and `rest` callbacks, and I suppose you could call `$.pep.unbind()` in one of those.

**Comment by aidan2129** [comment]
Yeah i found another solution anyway was just had to write a check for the height of the object changing then set it thanks for that :)
