### ISSUE TITLE
Dragging hidden content

### ISSUE THREAD

**Issue by Ruplahlava** [briangonzalez/jquery.pep.js#54]
Hi, i had tried to do a simple draggable gallery, draggable element would be ul inside div. 
Parent has overflow:hidden. But when i try to set pep's constrainTo parent it just stops working. csstransition is false.
Is there any possibility to solve it, or this is just not possible using pep?

**Comment by rkoppola** [comment]
Hi Brian, I have the same issue. Could you please provide me the code to solve this issue.

thanks
