### ISSUE TITLE
No way to override pep's placement functionality

### ISSUE THREAD

**Issue by KorvinSzanto** [briangonzalez/jquery.pep.js#90]
I'm pretty certain that the `place` property isn't only there to act as an opposite `deferPlacement` property.

I've crudely thrown in `if (this.options.place) { ... }` to ensure that pep doesn't do the placement at this point, but my solution is hacky. Is this something you'd want for the upstream?

**Comment by BazingaRoot** [comment]
> Ahh, I see. I guess in that case you'd want to set `place: false` then place the object before you called pep on the object.
> 
> ```js
> // Grab object.
> var $el = $('.el');
> 
> // Place it.
> $el.css({ position: 'absolute', top: randomTopVal, left: randomLeftVal  })
> 
> // Pep it.
> $el.pep({ place: false })
> ```

can you please elaborate on where to write these line
